.TH MW 1 mutt-wizard
.SH NAME
mw \- mutt-wizard \- E-Mail-Konten für neomutt und isync automatisch konfigurieren
.SH ÜBERSICHT
.B mw
[
.I OPTIONEN
]
.SH BESCHREIBUNG
.B mw
nimmt ein Benutzer-E-Mail-Konto und richtet dafür eine terminalbasierte E-Mail-Schnittstelle mit
.B neomutt
ein. Dies kann Offline-E-Mails mit
.B isync/mbsync
und Konfigurationen für
.B msmtp
zum Versenden von E-Mails umfassen, sowie automatisch verschlüsselte und mit
.B pass
gespeicherte Passwörter.
.SH BEFEHLE
.TP
.B -a ihre@email.com
ein E-Mail-Konto hinzufügen
.TP
.B -l
alle von mutt-wizard konfigurierten E-Mail-Konten auflisten
.TP
.B -d
ein bereits konfiguriertes Konto auswählen und dessen Konfiguration entfernen
.TP
.B -D ihre@email.com
ein konfiguriertes Konto ohne Bestätigung entfernen
.TP
.B -y ihre@email.com
E-Mails für ein E-Mail-Konto herunterladen und hochladen
.TP
.B -Y
alle E-Mail-Konten synchronisieren
.TP
.B -t 15
einen Cronjob umschalten, der Ihre E-Mails alle 15 Minuten synchronisiert (oder eine andere Zahl unter 60)
.TP
.B -T
einen Cronjob umschalten, ohne Minuten zwischen Synchronisationen anzugeben
.TP
.B -r
Konten-Kurznummern neu ordnen
.SH OPTIONEN ZUM HINZUFÜGEN VON KONTEN
Diese können in der Befehlszeile angegeben werden, andernfalls werden Sie nach den notwendigen Informationen gefragt. mutt-wizard kennt die IMAP/SMTP-Serverinformationen für die meisten E-Mail-Anbieter, daher ist deren Angabe meist überflüssig.
.TP
.B -u max
Konto-Anmeldename/Benutzername, falls erforderlich und anders als die E-Mail-Adresse.
.TP
.B -n Max
Echter Name, der in E-Mails erscheinen wird. Sollte in Anführungszeichen gesetzt werden, wenn er aus mehreren Wörtern besteht.
.TP
.B -m Zahl
Legt eine maximale Anzahl von Nachrichten fest, die offline gespeichert werden sollen.
.TP
.B -i
IMAP/POP-Serveradresse
.TP
.B -I
IMAP/POP-Serverport (wird als 993 für IMAP und 995 für POP angenommen, wenn nicht angegeben)
.TP
.B -s
SMTP-Serveradresse
.TP
.B -S
SMTP-Serverport (wird als 465 angenommen, wenn nicht angegeben)
.TP
.B -x
Kontopasswort. Sie werden interaktiv nach dem Passwort gefragt, wenn diese Option nicht angegeben wird.
.B -P
Pass-Präfix. Das Passwort wird mit pass unter <passprefix><email> gespeichert
.SH ANDERE OPTIONEN
.TP
.B -f
Erzwingt die Kontoerstellung und errät Postfächer, ohne zu versuchen, eine Verbindung zum Server herzustellen. Andernfalls werden die konfigurierten Kontoeinstellungen nicht dauerhaft sein, wenn keine Verbindung hergestellt werden kann.
.TP
.B -o
Erstellt Einstellungen für ein Konto, das nur online ohne E-Mail-Synchronisationsfähigkeiten verwendet werden soll. Ohne
.B -f
wird während der Einrichtung trotzdem versucht, eine Verbindung herzustellen, um Postfächer zu entdecken.
.TP
.B -X
Beim Entfernen eines E-Mail-Profils mit entweder
.I -d
oder
.I -D
auch die lokalen E-Mails löschen (löscht die E-Mails nicht auf dem Server).
.TP
.B -p
Verwendet das POP-Protokoll anstelle von IMAP. Erfordert
.I mpop
zum Herunterladen von E-Mails nach der Konfiguration. Serverdetails können trotzdem mit den Optionen
.I -i
und
.I -I
angegeben werden, als wäre es IMAP.
.SH DETAILS
.TP
.B mailsync
mutt-wizard ruft ein Skript
.I mailsync
auf, um E-Mails zu synchronisieren. Dieses Skript indiziert zusätzlich neue E-Mails mit notmuch und benachrichtigt Sie, wenn neue E-Mails eingetroffen sind. Wenn Sie seine zusätzlichen Funktionen umgehen möchten, können Sie immer einfach
.I mbsync -a
ausführen, um Ihre E-Mails direkt zu synchronisieren.
.TP
.B E-Mail-Speicherort
Wenn der Benutzer sich entscheidet, Offline-E-Mails mit
.B isync
zu behalten, werden diese in
.I ~/.local/share/mail/
gespeichert.
.B notmuch
kann verwendet werden, um diese E-Mails zu indizieren und zu durchsuchen, indem dieses Verzeichnis beim ersten Ausführen von
.B notmuch setup
angegeben wird.
Wenn Sie notmuch noch nicht eingerichtet haben, wird mutt-wizard es automatisch im Hintergrund einrichten, wenn Sie zum ersten Mal ein Konto hinzufügen.
.TP
.B muttrc-Dateien
mutt-wizard erstellt für jedes erstellte Konto eine muttrc-Datei mit kontospezifischen Details. Diese erscheinen in
.I ~/.config/mutt/accounts/
und können bei Bedarf vom Benutzer bearbeitet werden. Beachten Sie, dass der mutt-wizard diese Dateien auch einbindet und die Bindungen zum Wechseln zwischen ihnen erstellt. Diese erscheinen in Ihrer Standard-
.I ~/.config/mutt/muttrc
Datei.
.TP
.B E-Mail-Löschung
Die Löschaktion von mutt-wizard löscht Konfigurationsdateien und
.I nicht
heruntergeladene E-Mails aus Sicherheits- (und Zeit-)gründen. Wenn Sie heruntergeladene E-Mails löschen möchten, tun Sie dies manuell, indem Sie sie aus dem oben genannten Verzeichnis entfernen.
.TP
.B Standardeinstellungen
Der mutt-wizard hat viele Standardeinstellungen, die sich darauf konzentrieren, ihn optisch ansprechend zu gestalten und mehr vim-ähnliche Bindungen bereitzustellen. Diese finden Sie in
.I /usr/local/share/mutt-wizard/mutt-wizard.muttrc
und die Standard-Mailcap-Datei finden Sie in
.I
/usr/local/share/mutt-wizard/mailcap.
Jede dieser Einstellungen kann in
.I ~/.config/mutt/muttrc
überschrieben werden, aber beachten Sie, dass Ihre überschreibenden Bindungen nach dem Einbinden der
.I
mutt-wizard.muttrc
Datei erscheinen sollten.
.TP
.B Erkennen von Servereinstellungen
mutt-wizard hat ein Repository von E-Mail-Diensten und deren Serverinformationen, das in
.I /usr/local/share/mutt-wizard/domains.csv
gespeichert ist und zur automatischen Konfiguration von E-Mail-Einstellungen verwendet wird.
Wenn Ihr E-Mail-Anbieter dort nicht gefunden wird, werden Sie aufgefordert, die IMAP- und SMTP-Serverinformationen Ihres E-Mail-Dienstes einzugeben, die normalerweise durch eine Online-Suche gefunden werden können.

Wenn Sie bei der Entwicklung von mutt-wizard für andere helfen möchten, sind Sie eingeladen, diese Serviceinformationen zu
.I domains.csv
auf den Github- <https://github.com/lukesmithxyz/mutt-wizard> oder Gitlab- <https://gitlab.com/lukesmithxyz/mutt-wizard> Seiten von mutt-wizard hinzuzufügen.
.TP
.B Gmail-Konten
Google wird von Ihnen verlangen, dass Sie "weniger sichere" (Drittanbieter-) Anwendungen zulassen oder die Zwei-Faktor-Authentifizierung entfernen, um auf ihre IMAP-Server zugreifen zu können, um Ihre E-Mails herunterzuladen. Wenn Sie Gmail verwenden, stellen Sie sicher, dass Sie dies vor dem Ausführen von mutt-wizard erledigen <https://support.google.com/accounts/answer/6010255>.
.TP
.B Unternehmens- und Universitätskonten
Viele Universitäten und Unternehmen hosten möglicherweise die E-Mails ihrer Domain über Google oder einen anderen Dienst. Dies erfordert oft ein spezielles IMAP/SMTP-spezifisches Passwort, das Sie generieren und verwenden müssen. Auch hier kann mutt-wizard mit diesen Systemen umgehen, aber erst nachdem sie eingerichtet wurden.
.TP
.B Passwort-Entschlüsselung
mutt-wizard verwendet
.I pass
und daher
.I gpg
zur Entschlüsselung Ihrer Passwörter. Vorausgesetzt, Ihr GPG-Schlüssel hat ein Passwort, kann dies bedeuten, dass Sie beim ersten Synchronisieren oder Senden von E-Mails in einer Sitzung nach Ihrem GPG-Passwort gefragt werden. Sobald Ihr Passwort zwischengespeichert ist, kann es später auch ablaufen.

Aufgrund dessen empfehle ich dringend das Programm
.I pam-gnupg
<https://github.com/cruegge/pam-gnupg>, das Ihr GPG-Passwort beim Login automatisch entsperrt und aktiv hält, und Ihnen somit mit mutt-wizard sicheren Zugriff auf alle Ihre E-Mail-Konten auf Ihrem System gibt, ohne jemals ein Passwort eingeben zu müssen.

Wenn Sie dieses Programm nicht verwenden möchten, können Sie auch die Zwischenspeicherzeit eines eingegebenen GPG-Passworts mit den Variablen
.I default-cache-ttl
und
.I max-cache-ttl
in Ihrer
.I
gpg-agent.conf
erhöhen.
.SH MUTT-WIZARD'S NEOMUTT-KONFIGURATION
Hier ist eine Liste nicht nur der besonderen Standardeinstellungen von mutt-wizard, sondern auch dessen, was Sie benötigen, um das Meiste aus E-Mail-Konten zu holen, die mit mutt-wizard konfiguriert wurden.
.TP
.B Farbe
Die Standardeinstellungen von mutt-wizard fügen den Nachrichten im Index Farbe hinzu und färben E-Mail-Details, um sie leichter erkennbar zu machen. Neue E-Mails werden zusätzlich zur typischen N-Markierung auch fett dargestellt.
.TP
.B Bewegung mit h/j/k/l
Verwenden Sie Vim-Tasten, um in E-Mails nach unten
.I j
oder nach oben
.I k
zu gehen, während
.I l
E-Mails öffnet, dann die Anhangsansicht, dann einen Anhang, während
.I h
die Umkehrung ist.
Während eine E-Mail geöffnet ist, gehen Sie mit
.I J
und
.I K
zur nächsten oder vorherigen E-Mail.
Im E-Mail-Index gehen
.I d
und
.I u
um eine halbe Seite nach unten und oben und
.I gg
und
.I G
ganz nach oben und ganz nach unten.
.TP
.B E-Mails durchsuchen
Wenn Sie
.B notmuch
mit Ihrem korrekten E-Mail-Verzeichnis konfiguriert haben (siehe oben), können Sie
.I Strg-f
ausführen, um nach E-Mails zu suchen, die eine beliebige Sequenz enthalten.
Auch ohne notmuch begrenzt
.I L
E-Mails und zeigt nur diejenigen mit der angegebenen Sequenz im Betreff, während
.I A
alle E-Mails anzeigt (dasselbe wie die Begrenzung auf "alle").
.TP
.B E-Mails löschen
.I D
löscht E-Mails, während
.I U
sie wiederherstellt (geben Sie die E-Mail-Nummer ein, um zu gelöschten E-Mails zu gelangen). Beachten Sie, dass
.I S
Ihren Posteingang speichert und die Löschung abschließt. Wenn Sie einen
.I Papierkorb
haben, werden gelöschte E-Mails dorthin verschoben. Wenn Sie möchten, dass sie diesen überspringen und einfach gelöscht werden, kommentieren Sie die Zeile
.I set trash
in der muttrc dieses Kontos aus oder entfernen Sie sie.
.TP
.B E-Mails senden
.I m
erstellt eine neue E-Mail-Nachricht;
.I r
antwortet auf die ausgewählte Nachricht;
.I R
antwortet allen auf die ausgewählte Nachricht und
.I f
leitet die ausgewählte Nachricht weiter.
.TP
.B E-Mail-Verfassungsbildschirm
Sobald Sie eine E-Mail geschrieben und den Puffer gespeichert haben, gelangen Sie zum Verfassungsbildschirm. Drücken Sie
.I a
um Anhänge hinzuzufügen, verwenden Sie
.I s/t/c/b/d
um Betreff/An/CC/BCC/Beschreibung zu ändern. Drücken Sie
.I S
um die Signatur/Verschlüsselung zu ändern. Drücken Sie
.I y
um die E-Mail zu senden.
.TP
.B E-Mail-Adressen mit abook speichern und automatisch vervollständigen
Installieren Sie die optionale Abhängigkeit abook und Sie können die E-Mail-Adresse des Absenders mit
.I a
speichern. Sobald dies geschehen ist, können Sie bei der Eingabe einer E-Mail/Kontakt-Aufforderung
.I Tab
drücken, um Kontakte zu finden, die Ihrer
Eingabe entsprechen. Obwohl abook oft mit mutt verwendet wird, ist es auch ein nützliches Programm für sich.
.TP
.B Zwischen Postfächern wechseln und E-Mails verschieben
Die Taste
.I g
kann mit mehreren anderen Tasten kombiniert werden, um automatisch zu einem anderen Postfach zu wechseln: gi: Posteingang; gs: Gesendet; gd: Entwürfe; ga: Archiv; gS: Spam; gj: Junk; gt: Papierkorb. Diese Bindungen sind nur für Konten vorhanden, die die betreffenden Postfächer haben. Anstelle von
.I g
können Sie auch
.I C
drücken, um E-Mails zu kopieren oder
.I M
um E-Mails in dieselben Postfächer zu verschieben.
.TP
.B Zwischen Konten wechseln
mutt-wizard kann bis zu neun Konten konfigurieren, die jeweils mit der niedrigsten verfügbaren Nummer bei der Konfiguration nummeriert werden. Drücken Sie
.I i
gefolgt von der Nummer eines Kontos, um zu diesem Konto zu wechseln: i2, i5, usw.
.I Strg-b
um ein Menü zu öffnen, um eine URL auszuwählen, die Sie in Ihrem Browser öffnen möchten.
.TP
.B Seitenleiste
mutt-wizard aktiviert standardmäßig die Seitenleiste, die die Postfächer Ihres Kontos mit E-Mail-Zählungen anzeigt.
.I B
schaltet die Seitenleiste um. Bewegen Sie sich mit
.I Strg-k/j
auf und ab. Öffnen Sie ein Postfach mit
.I Strg-o.
.TP
.B Weitere Informationen
Denken Sie daran, dass Sie jederzeit
.I ?
in neomutt drücken können, um eine Liste aller Tastenbindungen und Funktionen zu erhalten. Diese Liste kann auch für verschiedene Kontextmenüs variieren.
.SH AUTOREN
Geschrieben von Luke Smith <luke@lukesmith.xyz> ursprünglich im Jahr 2018.
.SH LIZENZ
GPLv3
.SH SIEHE AUCH
.BR mailsync (1),
.BR neomutt (1),
.BR neomuttrc (1)
.BR mbsync (1),
.BR mpop (1),
.BR msmtp (1),
.BR notmuch (1),
.BR abook (1)
